git:
  depth: false
branches:
  only:
    - master
language: java
jdk:
- openjdk8
services:
- docker
cache:
  directories:
  - $HOME/.m2
env:
  global:
  # AWS_ACCESS_KEY_ID
  - secure: "iUiRSTm4N1s754n9PyZY0LmaV80nrq4djtQtcnmMzUOqHytQSqkjP20Z0qP52BCgFspTjTQEMfdKYQgxo1uB12Kvpw+RxRmj3xJ1VPAunDt17tmuB4Z2bLRwW4Nla1fAG4Hfd/pVPMMrGmiqvfiHPI/EMnjuZ4Meix4wHIN8c9CYVdDbOmDJiba1werFEchJVIyVYh5F88DWQZ4Ed8doz7t3c32IENHmgb+Q/lRmmDh1Z8QftUc1IrGY7eG2xurnqw0KuFPnTU0vw7gLsxF9vEkWnwW3mu18PAS1FbCO514aWBr53tu9+WhXvwQyaHHUtpiufZHb9z4AfbxA/E3lnLFAKYTqIQ1d87mIWT0qdJ+8b/7VaOSrbYFDlFWFJmUsI5XR2wmvBHgzxoO7t34ux3SE/bbQ6yXI5z9RPRSCnV9O6bFgnFUOare4V/emZQ0ZvvoDflpese+1dDJaGi8DC+0HrYT62dn4l9kITX4KjFO15TQsTDvgl3hbocBJlLhB9N86I01Hd3icEF3vD4UR4TCC/aMtBw0VVrLa7wFi6/61r3DgTRINOqexHlhNnf5bCPF/pTn6GB9wjR/X6xe5+FxhXzDpr3m9leXPQmSFmJl9iCCJJUeCOLyicoqiEC3itjXBKQHn3FInya3ozoozwQJthgWqa/ZmmBBdYnPuX98="
  # AWS_SECRET_ACCESS_KEY
  - secure: "W2QkSfmUOhcyAbjezKIPL8UcCBT/YHucrlda+1WcfjAfJvsabVM+F9FFNRZen/SdjdxreeANgoW/23YmDQHZaRzbRFa2Iy/HGx5HlCzwZdbySTTiKm8xlusVxhcQbIOYfB8XZ17TqldAZ6FjskOcIeU3suqtrIx/Rv4eOiaPU1IIu0ossJWMbUjvzyoj6JQp1ey51XOSXBDTWk8lAu04kgpUsIokdUC8J+ytffQ9dk1VPw/iE0K5ls4sMeZBLsu3W8Uf7UWfIkPRPNZiyGXfsyk8EfaN4tC2CmQ29fDPRWaZtzqR5b8WEwauMF5TfYw/wyv8mtaPSE/XhR6V8mc35q7jI79Yz7gB5bAbhzi8eAhrxslI0pAZEs9jmyzNZFTMVB486qudZQXrU3mf+ywFVQINaDZu94qqVOTTDwYXCLwJKOLe0hCokzsFXwFLEZ/287TlgcgGPsHzxMUuSywx+qtXPFDeghOXmoAILBILGH7jAPD/nHauWo5XXtaLPFG6hoQIVZopdgy3QTN4UYIlsZSNtXrSLm6L8Vi7fw7lyVvgoPhQQgiQYVXtwB1Z19qMZKdHTzpz5FpG+fznl1eqN2LDc6ucaNxT45WbYRltThMR+T8t3cf88aHSqnaKQUgxyKFPtfvaWqqsLlKwtxpm3DpVslO+snBYZLJ5gnoAju8="

install:
- git clone https://github.com/Opetushallitus/ci-tools.git
- source ci-tools/common/setup-tools.sh
- export ARTIFACT_NAME="lokalisointi"

script:
- mvn clean package -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}

- mv lokalisointi/target/lokalisointi-*.war $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}.war
- cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/

- export BASE_IMAGE="baseimage-war-openjdk8:master"
- ./ci-tools/common/pull-image.sh
- ./ci-tools/build/build-war.sh $ARTIFACT_NAME

deploy:
  provider: script
  script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
  on:
    all_branches: true
