sudo: required
language: java
jdk:
- openjdk8
services:
- docker
cache:
  directories:
  - $HOME/.m2
env:
  global:
  # AWS_ACCESS_KEY_ID
  - secure: "hWDTsKxiI+GqIdXmlk26/9bKI5de8IFf33q6gmcVngBn5WnUTk1+p9Eg2g1SoHko7oUdhkrl0j/mcQhUk0vYzlrFaewVcGJHAUxR+AGuzIdPEAQLygonz4Q16U2DFjKWplKO3K3XIlvIevYlwliFlWn99CMMRUwE6ulBVLFNN3KqZylokew+Ye8vGaufHs0Sso7pJSmEVvwjkdc4os4S8Y9XjpPML5eUeO6xhQCszi9ni5Mbl+7I3kNDQ8IreBiLCTgS555lmtS1nHkjsoQKzrT2Jq42N6NDP7Z42O8QyKt6sp8c9P9hPcecXU9HY3Ugvcu+zWk28nZEjKrbrPenMJUA8YVPuRaSz7d7hO/1oDYNEczKFlgbAiV3EMNCS/C8gATZcQKWFkZFc6rsgdRnvb/yfPpp5XbK1ldniHw4MZvTi8Ir5ok9v+1dxItbvqsV0PhXuvVKBmoCbw4abJUVT0/nHbTUARgKu5cSE4pw/VJ/wRnTDWWOp2BASaLbpFvYCgrw4lNiG/yd3We6SBtW3MplfkmdygNf6xqWeO/53O945u9je++PKfwm90OweV62Y8htoNbZyNDA1rN8JJ1tPuAkLfNTUOKwDgn6K+WNFJCS1WQV4DLFUAiP4JoDrKjIE3XWfyJ2WYhTgqXcRxrzcq/q7/eCprDJikLMmc+APxc="
  # AWS_SECRET_ACCESS_KEY
  - secure: "RqqOZNtvydx/h4G+Jy4H/aL1Wm5YwWPS3Bx5lI1ozrJ7Ac4Gz1KU1Lyn8iCC36rGisueUGx8fVTFRvQIyWWxKhgl7xPs8A5sWdYcow+V4sKljVmFB9FyK+Bfs7CJl4nKV+aAPiR12eb3tdsnjkF5N1GRUTjGbSgUfOR1WvEJETdQvQf9x+HEOqyQLMH+WtL6igA6k2QPJxxuCMJJ3JtyniRbT6r1wsEyvGKVkdBQwDEMzzfzm54/M8BvM2JCQr0AboItcUEfoXsi9sSJ+Am0EAiPPlZfWzRsWyU0cU1/7aBDyZKbmnFguMVVgiZtnJnhu9bnYDbJmP0hVOXAYwG8RGvemuSafBV4gb0luMbe2Y2fjPRtQnHer5c3yegUslatd3ll1segznpE3PJosCnv2Du73KRLvuFtPa78cD76Ke7Ak+jcqCOOgBCTJcZsZPNGyqZ1u1JC+kQf1rs0SVHdgZBlrxtYXRABb18/kN/ISm0Jkv9vozf/iyr99rxlPE3TFwGWttqrJ0ztxf8SOPsxi8cQqKV2BVqZWRz78wAbNKhPMMZA+4x+md4Ml2M7wX35I2NEpLoUJ8P/DKvd2eiRuIOXAb26pW+I5FN30M6BCkMFfo26oS1+ayFKAUlRTWD0XzM4xmlF8lsA4DwjUsPiST7ghfLSK54UZbqc63C3Ias="

install:
- git clone https://github.com/Opetushallitus/ci-tools.git
- source ci-tools/common/setup-tools.sh
- export ARTIFACT_NAME="lokalisointi"

script:
- mvn clean package -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}

- mv lokalisointi/target/lokalisointi-*.war $DOCKER_BUILD_DIR/artifact/${ARTIFACT_NAME}.war
- cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/

- export BASE_IMAGE="baseimage-war-openjdk8:master"
- ./ci-tools/common/pull-image.sh
- ./ci-tools/build/build-war.sh $ARTIFACT_NAME

deploy:
  provider: script
  script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
  on:
    all_branches: true
